"""Fix encrypted field names

Revision ID: 4492e569ccf9
Revises: b085f24b1618
Create Date: 2026-02-04 17:15:01.556742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4492e569ccf9'
down_revision: Union[str, Sequence[str], None] = 'b085f24b1618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_genomic_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('allow_research',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('genomic_data')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userprofile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genomic_data', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('allow_research',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.drop_column('encrypted_genomic_data')

    # ### end Alembic commands ###
